---
title: "Immigration Report"
author:
- familyname: Dingorkar
  othernames: Priya Ravindra
  address: Monash University
  email: pdin0008@student.monash.edu
  qualifications:  BE in Computer Enginnering, Pursing Master of Business Analytics
  correspondingauthor: true
- familyname: Babu
  othernames: Aarathy
  address: Monash University
  email: abab0012@student.monash.edu
  qualifications:  B.Tech
- familyname: Wang
  othernames: Junhao
  address: Monash University
  email: jwan0296@student.monash.edu
  qualifications: Accounting
- familyname: XXX (Please add your details Dilinie)
  othernames: XXX
  address: XXX
  email: XXX
  qualifications:  XXX
  correspondingauthor: true
department: ETC5513, Group 11\newline Junhao &\newline Aarathy &\newline Dilinie &\newline Priya
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(scales)
library(naniar)

```



\section*{Introduction}

\section*{Abstract}

\section*{Methodology}

\section*{Gender Gap in Migration}


```{r dataread , echo=FALSE, message=FALSE}

file1 <- read.csv("data/DIOC_2015_16_File_A_1.csv")

```

```{r datacleaning , echo = FALSE, message = FALSE}
whomigrates<- file1 %>% 
  mutate(edu_lfs = as.character(edu_lfs),
         age_lfs=as.character(age_lfs),
         sex=as.character(sex),
         national=as.character(national),
         oecd=as.character(oecd),
         oecdb=as.character(oecdb),
         fborn=as.character(fborn)
         ) %>% 
         mutate(
           age_lfs = case_when(
    str_detect(age_lfs,"0") ~ "0-14",
     str_detect(age_lfs,"1") ~ "15-24",
 str_detect(age_lfs,"2") ~ "25-64",
 str_detect(age_lfs,"3") ~ "65+",
 str_detect(age_lfs,"12") ~ "15-84",
 str_detect(age_lfs,"99") ~ "Unknown" 
 )) %>%
  mutate(sex = case_when(
   str_detect(sex,"1") ~ "Male",
   str_detect(sex,"2")~ "Female"
 )) %>%
  mutate(edu_lfs = case_when(
    str_detect(edu_lfs,"1")~"low",
    str_detect(edu_lfs,"2")~"medium",
    str_detect(edu_lfs,"3")~"high",
    str_detect(edu_lfs,"99")~"unknown"
  )) %>% 
      mutate(national = case_when(
    str_detect(national,"0") ~ "Foreigner",
     str_detect(national,"1") ~ "National",
     str_detect(national,"99")~"unknown"
    
  )) %>% mutate(oecd = case_when(
    
    str_detect(oecd,"0") ~ "Non member",
     str_detect(oecd,"1") ~ "Member"
    
  )) %>% mutate(oecdb = case_when(
    
    str_detect(oecdb,"0") ~ "Non member",
     str_detect(oecdb,"1") ~ "Member"
    
  )) %>% mutate(fborn = case_when(
    
    str_detect(fborn,"0") ~ " Native-born",
     str_detect(fborn,"1") ~ " Foreign-born ",
     str_detect(fborn,"99")~"unknown"
    
  )) %>% replace_with_na (replace =
                    list(edu_lfs = "unknown",
                         national = "unknown",
                         fborn = "unknown"
                        ))

```



```{r topdestinations, echo = FALSE, message = FALSE, warning=FALSE}

top_10 <- whomigrates %>%  mutate(
         sex=as.factor(sex),
         oecd=as.factor(oecd),#oecd resident
         oecdb=as.factor(oecdb),#oecd born
         age_lfs=as.factor(age_lfs),
         edu_lfs =as.factor(edu_lfs)
         ) %>% 
  group_by(country) %>% summarise(Immigrant_Count=sum(number,na.rm=T)) %>% arrange(desc(Immigrant_Count)) %>% head(10)  
  
  top_10 %>% 
   
    mutate( country =
    case_when(
    str_detect(country,"USA") ~ "United States of America",
    str_detect(country,"JPN") ~ "Japan",
    str_detect(country,"MEX") ~ "Mexico",
    str_detect(country,"DEU") ~ "Germany",
    str_detect(country,"TUR") ~  "Tunisia",
     str_detect(country,"FRA") ~  "France",
     str_detect(country,"GBR") ~  "United Kingdom",
     str_detect(country,"ITA") ~  "Italy",
     str_detect(country,"KOR") ~  "Korea",
     str_detect(country,"ESP") ~  "Spain",
  ))%>% rename(Country = country) %>%
  kable("latex", booktabs = T,caption="Top 10 destinations") %>% 
kable_styling(latex_options= c("striped","condensed"),full_width = F)

```



```{r gendergap, warning=FALSE,echo = FALSE, message = FALSE, fig.cap="Gender difference in migrant population in countries" , fig.width=10}

options(scipen=999)
gendergap <- whomigrates %>% 
  mutate(
         sex=as.factor(sex),
         oecd=as.factor(oecd),#oecd resident
         oecdb=as.factor(oecdb),#oecd born
         age_lfs=as.factor(age_lfs)
         ) %>% 
  group_by(sex,country)%>% summarise(n=sum(number,na.rm = T)) 
   
  gendergap %>% 
    ggplot(aes(x= fct_reorder(country,n),y=n,fill= sex) )+
    geom_col(position = "dodge")+ 
    theme_bw()+theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    scale_y_continuous(labels = comma) + xlab("Destination Country") + ylab("Number of Immigrants")
    



```




```{r agegap, warning=FALSE,echo = FALSE, message = FALSE, fig.cap="Gender difference in migrant population across age groups in countries " , fig.width=7}
agegap <- whomigrates  %>% 
  mutate(
         sex=as.factor(sex),
         oecd=as.factor(oecd),#oecd resident
         oecdb=as.factor(oecdb),#oecd born
         age_lfs=as.factor(age_lfs)
         ) %>%
 
  group_by(age_lfs,sex,country) %>% 
  summarise(total=sum(number,na.rm = T))
  `%notin%` <- Negate(`%in%`)
 agegap%>%  
  filter(age_lfs %notin% c("0-14","Unknown")) %>%
  ggplot(aes(x = country,y = total,fill = sex)) +

  
    geom_col(position = "dodge")+ 
    theme_bw()+theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    scale_colour_brewer(palette = "Set1")+ 
    scale_y_continuous(labels = comma) +
   facet_wrap(~age_lfs,nrow = 3) + ylab("Number of Immigrants") +
   xlab("Country")


```




